/** Localisation of the admin interface only. API values and form values are never changed. */
type Language = 'fr' | 'ht';

const ht: Record<string, string> = {
  'Vue d’ensemble': 'Apèsi jeneral',
  'Vue d’ensemble · DJR Akademi': 'Apèsi jeneral · DJR Akademi',
  'Statistiques principales': 'Estatistik prensipal yo',
  'Actions rapides': 'Aksyon rapid',
  'Ajouter un cours': 'Ajoute yon kou',
  'Ajouter un ebook': 'Ajoute yon liv dijital',
  'Ajouter un coaching': 'Ajoute yon sèvis konsèy',
  'Gérer les utilisateurs': 'Jere itilizatè yo',
  'Chargement du tableau de bord...': 'Tablo kontwòl la ap chaje...',
  'Réessayer': 'Eseye ankò',
  'Chiffre d’affaires': 'Revni',
  "Chiffre d'affaires": 'Revni',
  'Ventes': 'Lavant',
  'Commandes payées': 'Kòmand ki peye yo',
  'Utilisateurs': 'Itilizatè yo',
  'Utilisateur': 'Itilizatè',
  'Réservations': 'Rezèvasyon yo',
  'Sessions coaching': 'Sesyon konsèy yo',
  'Commandes récentes': 'Dènye kòmand yo',
  'Nouveaux utilisateurs': 'Nouvo itilizatè yo',
  'Prochains coachings': 'Pwochen sesyon konsèy yo',
  'Voir toutes les commandes': 'Gade tout kòmand yo',
  'Voir tous les utilisateurs': 'Gade tout itilizatè yo',
  'Voir les réservations': 'Gade rezèvasyon yo',
  'Aucune séance à venir pour le moment.': 'Pa gen okenn sesyon ki gen pou fèt pou kounye a.',
  'Cours': 'Kou',
  'Cours débloqués': 'Kou ki aksesib yo',
  'Cours gratuit': 'Kou gratis',
  'Ebook': 'Liv dijital',
  'Ebooks': 'Liv dijital yo',
  'E-books': 'Liv dijital yo',
  'Ebook gratuit': 'Liv dijital gratis',
  'Ebooks débloqués': 'Liv dijital ki aksesib yo',
  'Offres groupées': 'Òf gwoupe yo',
  'Offre groupée': 'Òf gwoupe',
  'Offres et regroupements': 'Òf ak pakè yo',
  'Total des offres groupées': 'Kantite òf gwoupe',
  'Offres actives': 'Òf aktif yo',
  'Nouvelle offre groupée': 'Nouvo òf gwoupe',
  'Créer votre premier bundle': 'Kreye premye pakè w la',
  'Aucune offre groupée trouvée': 'Pa jwenn okenn òf gwoupe',
  'Prix Pack': 'Pri pakè a',
  'Prix du pack (HTG) *': 'Pri pakè a (HTG) *',
  'Prix fixé pour ce pack :': 'Pri ki fikse pou pakè sa a :',
  'Produits inclus': 'Pwodui ki ladan l yo',
  'Produits Inclus': 'Pwodui ki ladan l yo',
  'Réduction': 'Rabè',
  'Réduction moyenne': 'Rabè mwayen',
  'Valeur séparée des produits :': 'Valè pwodui yo apa :',
  'Économie client :': 'Lajan kliyan an ekonomize :',
  'Publier immédiatement cette offre groupée': 'Pibliye òf gwoupe sa a tousuit',
  'Rendre ce pack visible immédiatement sur la page d’accueil et dans le catalogue.': 'Fè pakè sa a parèt tousuit sou paj dakèy la ak nan katalòg la.',
  'Rendre ce pack visible immédiatement sur la page d\'accueil et dans le catalogue.': 'Fè pakè sa a parèt tousuit sou paj dakèy la ak nan katalòg la.',
  'Regroupez plusieurs formations et e-books avec une réduction attractive pour vos apprenants.': 'Mete plizyè kou ak liv dijital ansanm epi ofri elèv yo yon bon rabè.',
  'Commandes': 'Kòmand yo',
  'Commandes · DJR Akademi Admin': 'Kòmand yo · Administrasyon DJR Akademi',
  'Consultez les achats et paiements de vos clients.': 'Konsilte acha ak peman kliyan ou yo.',
  'Aucune commande trouvée.': 'Pa jwenn okenn kòmand.',
  'Chargement des commandes…': 'Kòmand yo ap chaje…',
  'Commande expirée': 'Kòmand lan ekspire',
  'Paiement': 'Peman',
  'Paiement & Transaction': 'Peman ak tranzaksyon',
  'Paiement en attente': 'Peman annatant',
  'Paiement validé — accès à vérifier': 'Peman valide — aksè pou verifye',
  'Payé': 'Peye',
  'Payées': 'Peye',
  'En attente': 'Annatant',
  'En cours': 'Ankou',
  'Expiré': 'Ekspire',
  'Expirées': 'Ekspire',
  'Échoué': 'Echwe',
  'Échouées': 'Echwe',
  'Annulées': 'Anile',
  'Confirmées': 'Konfime',
  'Terminées': 'Fini',
  'Réservation : Confirmée': 'Rezèvasyon : konfime',
  'La tentative de paiement a échoué. Aucun accès n’a été accordé.': 'Tantativ peman an echwe. Yo pa bay okenn aksè.',
  "La tentative de paiement a échoué. Aucun accès n'a été accordé.": 'Tantativ peman an echwe. Yo pa bay okenn aksè.',
  'La transaction est en cours de traitement par le fournisseur de paiement.': 'Founisè peman an ap trete tranzaksyon an.',
  'Le délai de paiement est dépassé. La commande a été annulée.': 'Delè peman an pase. Kòmand lan anile.',
  "Le paiement est validé. L'accès a été débloqué automatiquement dans l'espace client.": 'Peman an valide. Kliyan an jwenn aksè otomatikman nan espas li.',
  'L’API n’a pas confirmé l’octroi de l’accès pour cette commande.': 'API a poko konfime aksè pou kòmand sa a.',
  'Client': 'Kliyan',
  'Produit': 'Pwodui',
  'Produit Acheté': 'Pwodui ki achte',
  'Produit / Commande': 'Pwodui / Kòmand',
  'Produit concerné :': 'Pwodui ki konsène a :',
  'Produit ou cours débloqué :': 'Pwodui oswa kou ki vin aksesib :',
  'Montant': 'Montan',
  'Montant total :': 'Montan total :',
  'Moyen de paiement :': 'Mwayen peman :',
  'Date du paiement :': 'Dat peman an :',
  'Référence': 'Referans',
  'Statut du paiement :': 'Estati peman an :',
  'Accès au cours : Accordé': 'Aksè nan kou a : akòde',
  "Accès à l'ebook : Accordé": 'Aksè nan liv dijital la : akòde',
  'Accès aux contenus du bundle : Accordé': 'Aksè nan kontni pakè a : akòde',
  'Accès suspendu (En attente de paiement)': 'Aksè sispann (peman annatant)',
  'Détails': 'Detay',
  'Voir le détail': 'Gade detay yo',
  'Voir le client': 'Gade kliyan an',
  'Voir le profil': 'Gade pwofil la',
  'Voir la réservation': 'Gade rezèvasyon an',
  'Voir la page': 'Gade paj la',
  'Voir la page publique': 'Gade paj piblik la',
  "Voir l'offre": 'Gade òf la',
  'Voir le programme': 'Gade pwogram nan',
  'Voir': 'Gade',
  'Tout voir': 'Gade tout',
  'Page publique': 'Paj piblik',
  'En ligne': 'Sou entènèt',
  'Actif': 'Aktif',
  'Actifs': 'Aktif',
  'Désactivé': 'Dezaktive',
  'Désactivés': 'Dezaktive',
  'Désactiver': 'Dezaktive',
  'Réactiver': 'Reaktive',
  'Désactiver l’utilisateur': 'Dezaktive itilizatè a',
  "Désactiver l'utilisateur": 'Dezaktive itilizatè a',
  'Réactiver l’utilisateur': 'Reaktive itilizatè a',
  "Réactiver l'utilisateur": 'Reaktive itilizatè a',
  'Désactiver cet utilisateur ?': 'Dezaktive itilizatè sa a ?',
  'Gérez les utilisateurs et leurs accès.': 'Jere itilizatè yo ak aksè yo.',
  'Aucun utilisateur trouvé pour cette recherche.': 'Pa jwenn okenn itilizatè pou rechèch sa a.',
  'Chargement des utilisateurs…': 'Itilizatè yo ap chaje…',
  'Chargement du profil utilisateur...': 'Pwofil itilizatè a ap chaje...',
  'Utilisateur introuvable dans Appwrite.': 'Pa jwenn itilizatè sa a nan Appwrite.',
  'Retour aux utilisateurs': 'Retounen nan lis itilizatè yo',
  'Retour à la liste des utilisateurs': 'Retounen nan lis itilizatè yo',
  'Date d’inscription': 'Dat enskripsyon',
  "Date d'inscription": 'Dat enskripsyon',
  'Donner un accès': 'Bay aksè',
  'Donner accès': 'Bay aksè',
  'Aucun accès': 'Pa gen aksè',
  'Type d’accès': 'Kalite aksè',
  "Type d'accès": 'Kalite aksè',
  'Se connecter comme cet utilisateur': 'Konekte kòm itilizatè sa a',
  'Accès': 'Aksè',
  'Cours · Administration': 'Kou · Administrasyon',
  'Créez et gérez vos formations.': 'Kreye epi jere kou ou yo.',
  'Créer un cours': 'Kreye yon kou',
  'Nouveau cours': 'Nouvo kou',
  'Nouveau cours · Administration': 'Nouvo kou · Administrasyon',
  'Formation introuvable.': 'Pa jwenn kou sa a.',
  'Chargement de la formation...': 'Kou a ap chaje...',
  'Aucun cours trouvé pour cette recherche.': 'Pa jwenn okenn kou pou rechèch sa a.',
  'Retour aux cours': 'Retounen nan lis kou yo',
  '← Retour aux cours': '← Retounen nan lis kou yo',
  'Rendre la formation visible au catalogue': 'Fè kou a parèt nan katalòg la',
  'Structurez le contenu de votre formation.': 'Òganize kontni kou ou a.',
  'Remplissez les informations ci-dessous pour créer votre formation.': 'Ranpli enfòmasyon ki anba yo pou kreye kou ou a.',
  'Informations générales': 'Enfòmasyon jeneral',
  'Informations générales et tarification.': 'Enfòmasyon jeneral ak pri.',
  '1. Informations générales': '1. Enfòmasyon jeneral',
  '2. Tarification & Paiement': '2. Pri ak peman',
  'Programme': 'Pwogram',
  'Modules et leçons': 'Modil ak leson yo',
  'Module': 'Modil',
  'Ajouter un module': 'Ajoute yon modil',
  '+ Ajouter un module': '+ Ajoute yon modil',
  '+ Créer un module': '+ Kreye yon modil',
  'Ajouter une leçon': 'Ajoute yon leson',
  'Aucun module créé.': 'Poko gen modil ki kreye.',
  "Aucun module pour l'instant.": 'Poko gen modil.',
  'Cliquez sur "Ajouter un module" pour démarrer le programme.': 'Klike sou « Ajoute yon modil » pou kòmanse pwogram nan.',
  'Gérer le contenu et les leçons': 'Jere kontni ak leson yo',
  'Gérer les leçons': 'Jere leson yo',
  'Enregistrer les leçons': 'Anrejistre leson yo',
  'Titre de la leçon *': 'Tit leson an *',
  'Type de leçon': 'Kalite leson',
  'Leçon suivante →': 'Pwochen leson →',
  '← Leçon précédente': '← Leson anvan an',
  'Édition & Visualisation de la leçon': 'Modifye epi gade leson an',
  'Choisissez une leçon dans le menu de droite pour modifier son titre, son type ou visualiser immédiatement sa vidéo Vimeo.': 'Chwazi yon leson nan meni adwat la pou modifye tit li, kalite li oswa gade videyo Vimeo li.',
  'Sélectionnez une leçon dans le programme à droite': 'Chwazi yon leson nan pwogram ki adwat la',
  'Aucun contenu texte saisi pour cette leçon.': 'Pa gen tèks pou leson sa a.',
  'Contenu textuel de la leçon': 'Kontni ekri leson an',
  'Visualisation du texte': 'Gade tèks la',
  'Visualisation de la vidéo (YouTube / Vimeo Player)': 'Gade videyo a (YouTube / Vimeo)',
  'Aucune vidéo valide configurée': 'Pa gen okenn videyo valab ki konfigire',
  'Éditeur': 'Editè',
  'Mode Étudiant': 'Mòd elèv',
  'Vidéo': 'Videyo',
  'Texte': 'Tèks',
  '🎥 Vidéo (YouTube, Vimeo, MP4)': '🎥 Videyo (YouTube, Vimeo, MP4)',
  '📄 Contenu Texte': '📄 Kontni ekri',
  'Ebooks · DJR Akademi Admin': 'Liv dijital yo · Administrasyon DJR Akademi',
  'Créez et gérez vos ebooks.': 'Kreye epi jere liv dijital ou yo.',
  'Créer un ebook': 'Kreye yon liv dijital',
  'Nouvel ebook': 'Nouvo liv dijital',
  'Nouvel Ebook · DJR Akademi Admin': 'Nouvo liv dijital · Administrasyon DJR Akademi',
  'Modifier l’ebook': 'Modifye liv dijital la',
  "Modifier l'ebook": 'Modifye liv dijital la',
  'Ebook introuvable.': 'Pa jwenn liv dijital sa a.',
  'Aucun ebook trouvé.': 'Pa jwenn okenn liv dijital.',
  'Chargement de l’ebook...': 'Liv dijital la ap chaje...',
  "Chargement de l'ebook...": 'Liv dijital la ap chaje...',
  'Retour aux ebooks': 'Retounen nan lis liv dijital yo',
  'Ajoutez un nouvel ebook à votre catalogue.': 'Ajoute yon nouvo liv dijital nan katalòg ou a.',
  'Mettez à jour les informations et le fichier de votre ebook.': 'Mete enfòmasyon ak fichye liv dijital ou a ajou.',
  'Fichier de l’ebook (PDF uniquement)': 'Fichye liv dijital la (PDF sèlman)',
  "Fichier de l'ebook (PDF uniquement)": 'Fichye liv dijital la (PDF sèlman)',
  'Aucun PDF': 'Pa gen PDF',
  'PDF chargé': 'PDF chaje',
  'Format PDF stocké sur Appwrite Storage (jusqu’à 50 Mo)': 'Fichye PDF estoke sou Appwrite Storage (jiska 50 Mo)',
  "Format PDF stocké sur Appwrite Storage (jusqu'à 50 Mo)": 'Fichye PDF estoke sou Appwrite Storage (jiska 50 Mo)',
  'Cliquez pour sélectionner un fichier PDF ou glissez-déposez ici': 'Klike pou chwazi yon fichye PDF oswa trennen l depoze l isit la',
  'Cet ebook ne sera plus disponible dans votre catalogue.': 'Liv dijital sa a p ap disponib nan katalòg ou a ankò.',
  'Coaching · Administration': 'Sesyon konsèy · Administrasyon',
  'Pilotez vos offres et vos prochaines sessions depuis un seul endroit.': 'Jere òf ou yo ak pwochen sesyon yo yon sèl kote.',
  'Créer une offre de coaching': 'Kreye yon òf sesyon konsèy',
  'Créer une offre': 'Kreye yon òf',
  'Nouveau Service': 'Nouvo sèvis',
  'Nouveau Coaching · DJR Akademi Admin': 'Nouvo sèvis konsèy · Administrasyon DJR Akademi',
  'Aucune offre de coaching créée.': 'Poko gen okenn òf sesyon konsèy.',
  'Offre de coaching introuvable.': 'Pa jwenn òf sesyon konsèy sa a.',
  'Chargement des offres...': 'Òf yo ap chaje...',
  'Chargement des séances…': 'Sesyon yo ap chaje…',
  'Chargement des réservations...': 'Rezèvasyon yo ap chaje...',
  'Vos offres': 'Òf ou yo',
  'Toutes les offres': 'Tout òf yo',
  'Gérer les réservations': 'Jere rezèvasyon yo',
  'Réservations coaching · Administration': 'Rezèvasyon sesyon konsèy · Administrasyon',
  'À venir': 'K ap vini',
  'Heure du coach': 'Lè antrenè a',
  'Toutes les heures sont affichées selon l’heure locale du coach.': 'Tout lè yo parèt selon lè lokal antrenè a.',
  'Horaires & indisponibilités': 'Orè ak lè ki pa disponib',
  'Disponibilité': 'Disponibilite',
  'Durée': 'Dire',
  'Prix': 'Pri',
  'Définissez le titre, la durée et le tarif de votre nouvelle consultation 1-on-1.': 'Chwazi tit, dire ak pri nouvo konsiltasyon endividyèl ou a.',
  'Paramètres de réservation': 'Paramèt rezèvasyon',
  'Paramètres de Coaching': 'Paramèt sesyon konsèy',
  'Paramètres Coaching · Administration': 'Paramèt sesyon konsèy · Administrasyon',
  'Vérifier les paramètres': 'Verifye paramèt yo',
  'Les créneaux utilisent': 'Plas yo itilize',
  'Créneaux générés automatiquement': 'Plas ki kreye otomatikman',
  'Transmission automatique des liens de visioconférence et rappels clients.': 'Voye lyen videyo ak rapèl bay kliyan yo otomatikman.',
  'Vos paramètres de coaching ont été enregistrés avec succès !': 'Paramèt sesyon konsèy ou yo anrejistre avèk siksè !',
  'Support Client': 'Sipò kliyan',
  'Support Client · Administration DJR Akademi': 'Sipò kliyan · Administrasyon DJR Akademi',
  'Gestion des requêtes de support envoyées par les utilisateurs ayant passé une commande.': 'Jere demann asistans itilizatè ki te pase yon kòmand yo.',
  'Aucune demande de support trouvée.': 'Pa jwenn okenn demann asistans.',
  'Chargement des demandes de support...': 'Demann asistans yo ap chaje...',
  'Détails du Ticket de Support': 'Detay demann asistans lan',
  'Message de support': 'Mesaj asistans',
  'Message sélectionné par le client :': 'Mesaj kliyan an chwazi a :',
  'Message de réponse': 'Mesaj repons',
  'Réponse administrateur (visible dans l’espace support du client) :': 'Repons administratè a (kliyan an ap wè li nan espas asistans li) :',
  "Réponse administrateur (visible dans l'espace support du client) :": 'Repons administratè a (kliyan an ap wè li nan espas asistans li) :',
  'Passer En cours': 'Mete ankou',
  'Marquer Résolu': 'Make kòm rezoud',
  'Résolu': 'Rezoud',
  'Purge des anciens tickets': 'Efase ansyen demann yo',
  'Suppression définitive des tickets dépassant la date limite': 'Efase demann ki depase dat limit la nèt',
  'Supprimer les tickets de plus de :': 'Efase demann ki gen plis pase :',
  'tous les tickets': 'tout demann yo',
  'Ouvrir WhatsApp': 'Louvri WhatsApp',
  'Journaux de vérification': 'Jounal verifikasyon yo',
  'Journaux de vérification · DJR Akademi Admin': 'Jounal verifikasyon yo · Administrasyon DJR Akademi',
  'Détails du journal de vérification': 'Detay jounal verifikasyon an',
  'Historique et suivi de toutes les tentatives de déblocage d’accès par carte Lemon Squeezy ou MonCash / Natcash.': 'Istwa ak swivi tout tantativ pou jwenn aksè atravè kat Lemon Squeezy oswa MonCash / Natcash.',
  'Chaque tentative de déblocage d’accès par carte ou mobile apparaîtra ici en temps réel.': 'Chak tantativ pou jwenn aksè ak kat oswa telefòn ap parèt isit la tousuit.',
  'Aucun journal de vérification pour le moment': 'Poko gen okenn jounal verifikasyon',
  'Chargement des journaux de vérification…': 'Jounal verifikasyon yo ap chaje…',
  'Vérification': 'Verifikasyon',
  'Vérification de l’Accès': 'Verifikasyon aksè',
  "Vérification de l'Accès": 'Verifikasyon aksè',
  'Valeur saisie (e-mail / référence)': 'Valè yo te antre (imèl / referans)',
  'Identifiant du Projet': 'Idantifyan pwojè a',
  'ID du journal': 'ID jounal la',
  'ID utilisateur': 'ID itilizatè a',
  'ID Transaction :': 'ID tranzaksyon :',
  'Méthode': 'Metòd',
  'Origine': 'Orijin',
  'Horodatage': 'Dat ak lè',
  'Date et heure': 'Dat ak lè',
  'Détecté': 'Detekte',
  'Succès': 'Siksè',
  'SUCCÈS': 'SIKSÈ',
  'Échec': 'Echèk',
  'ÉCHEC': 'ECHÈK',
  'Échec de transaction': 'Tranzaksyon an echwe',
  'Tous les statuts (succès et échec)': 'Tout estati yo (siksè ak echèk)',
  'Succès uniquement (✓)': 'Siksè sèlman (✓)',
  'Échecs uniquement (✕)': 'Echèk sèlman (✕)',
  'Toutes les méthodes (carte et mobile)': 'Tout metòd yo (kat ak telefòn)',
  'Toutes méthodes': 'Tout metòd yo',
  'Mobile (MonCash)': 'Telefòn (MonCash)',
  'Carte (Lemon)': 'Kat (Lemon)',
  'Moniteur de santé': 'Siveyans sistèm nan',
  'Supervision Plopplop': 'Siveyans Plopplop',
  'Supervision Plopplop · DJR Akademi Admin': 'Siveyans Plopplop · Administrasyon DJR Akademi',
  'État de la connexion backend et identifiants du projet.': 'Eta koneksyon sèvè a ak idantifyan pwojè a.',
  'Erreurs API': 'Erè API',
  'Statut API': 'Estati API',
  'Statut et message de réponse': 'Estati ak mesaj repons lan',
  'Latence': 'Tan repons',
  'Latence Moyenne': 'Tan repons mwayen',
  'Temps réponse': 'Tan repons',
  'Taux de succès': 'Pousantaj siksè',
  'Infrastructure Appwrite': 'Enfrastrikti Appwrite',
  'Créations et vérifications de paiement enregistrées par le backend sécurisé.': 'Kreyasyon ak verifikasyon peman sèvè sekirize a anrejistre.',
  'Purge': 'Netwayaj',
  'Suppression de logs': 'Efase jounal yo',
  'Oui, supprimer les logs': 'Wi, efase jounal yo',
  'Confirmer la purge': 'Konfime netwayaj la',
  'Cette opération retirera définitivement les enregistrements de l’historique Plopplop pour alléger la base de données.': 'Aksyon sa a ap efase dosye ki nan istwa Plopplop yo nèt pou fè baz done a pi lejè.',
  "Cette opération retirera définitivement les enregistrements de l'historique Plopplop pour alléger la base de données.": 'Aksyon sa a ap efase dosye ki nan istwa Plopplop yo nèt pou fè baz done a pi lejè.',
  'Paramètres': 'Paramèt',
  'Paramètres généraux': 'Paramèt jeneral',
  'Paramètres généraux · DJR Akademi Admin': 'Paramèt jeneral · Administrasyon DJR Akademi',
  'Plateforme': 'Platfòm',
  'Gérez l’identité visuelle, les coordonnées de contact et la localisation globale de votre plateforme.': 'Jere aparans, enfòmasyon kontak ak lokalizasyon platfòm ou a.',
  "Gérez l'identité visuelle, les coordonnées de contact et la localisation globale de votre plateforme.": 'Jere aparans, enfòmasyon kontak ak lokalizasyon platfòm ou a.',
  'Identité de la plateforme': 'Idantite platfòm nan',
  'Logo de la plateforme': 'Logo platfòm nan',
  'Nom du site *': 'Non sit la *',
  'Slogan / Tagline': 'Slogan',
  'Nom officiel et slogan d’accroche de l’académie.': 'Non ofisyèl ak slogan akademi an.',
  "Nom officiel et slogan d'accroche de l'académie.": 'Non ofisyèl ak slogan akademi an.',
  'Coordonnées & Contact': 'Enfòmasyon kontak',
  'Contact WhatsApp Professionnel': 'Kontak WhatsApp pwofesyonèl',
  'Email de contact *': 'Imèl kontak *',
  'Fuseau horaire & Monnaie': 'Zòn lè ak lajan',
  'Fuseau horaire par défaut *': 'Zòn lè pa defo *',
  'Fuseau Horaire de Référence': 'Zòn lè referans',
  'Devise principale': 'Lajan prensipal',
  'Gourde Haïtienne': 'Goud ayisyen',
  'Région de référence pour les plannings et la facturation.': 'Rejyon referans pou orè ak fakti yo.',
  'Votre fuseau actif :': 'Zòn lè aktif ou a :',
  'Heure locale actuelle :': 'Lè lokal aktyèl la :',
  'Maintenance des achats': 'Antretyen sistèm acha a',
  'Bannière d’annonce (Top Banner)': 'Banyè anons (anlè paj la)',
  "Bannière d'annonce (Top Banner)": 'Banyè anons (anlè paj la)',
  'Message de la bannière': 'Mesaj banyè a',
  'Couleur de fond': 'Koulè fon an',
  'Couleur du texte': 'Koulè tèks la',
  'Affichez un message d’information ou une promotion tout en haut de votre site.': 'Afiche yon enfòmasyon oswa yon pwomosyon anlè sit ou a.',
  "Affichez un message d'information ou une promotion tout en haut de votre site.": 'Afiche yon enfòmasyon oswa yon pwomosyon anlè sit ou a.',
  'Bloque temporairement les achats, les inscriptions gratuites et les réservations de coaching. Les contenus déjà achetés restent accessibles.': 'Bloke acha, enskripsyon gratis ak rezèvasyon sesyon konsèy pou yon ti tan. Kontni moun te achte deja rete aksesib.',
  'Les clients verront un message leur demandant de réessayer plus tard.': 'Kliyan yo ap wè yon mesaj ki mande yo eseye ankò pita.',
  'Enregistrer les paramètres': 'Anrejistre paramèt yo',
  'Enregistrer les modifications': 'Anrejistre chanjman yo',
  'Enregistrer': 'Anrejistre',
  'Enregistrement...': 'Anrejistreman...',
  'Enregistrement…': 'Anrejistreman…',
  'Enregistrement en cours…': 'Anrejistreman ankou…',
  'Sauvegarde...': 'Anrejistreman...',
  'Chargement des paramètres de la plateforme...': 'Paramèt platfòm nan ap chaje...',
  'Annuler': 'Anile',
  'Fermer': 'Fèmen',
  'Fermer l’inspecteur': 'Fèmen enspektè a',
  "Fermer l'inspecteur": 'Fèmen enspektè a',
  'Modifier': 'Modifye',
  'Changer': 'Chanje',
  'Changer l’image': 'Chanje imaj la',
  "Changer l'image": 'Chanje imaj la',
  'Supprimer': 'Efase',
  'Suppression...': 'Efase...',
  'Suppression en cours...': 'Aksyon efasman ankou...',
  'Actualiser': 'Mete ajou',
  'Rafraîchir': 'Rafrechi',
  'Ajouter': 'Ajoute',
  'Gérer': 'Jere',
  'Actions': 'Aksyon',
  'Informations': 'Enfòmasyon',
  'Informations Client': 'Enfòmasyon kliyan',
  'Général': 'Jeneral',
  'Statut': 'Estati',
  'Tous les statuts': 'Tout estati yo',
  'Tous': 'Tout',
  'Toutes': 'Tout',
  'Tous les produits': 'Tout pwodui yo',
  'Précédent': 'Anvan',
  'Suivant': 'Apre',
  'Affichage de': 'Afiche',
  'Affichage de la page': 'Afiche paj la',
  'Date': 'Dat',
  'Heure': 'Lè',
  'Description': 'Deskripsyon',
  'Description globale *': 'Deskripsyon jeneral *',
  'Titre du cours *': 'Tit kou a *',
  'Titre de l’ebook *': 'Tit liv dijital la *',
  "Titre de l'ebook *": 'Tit liv dijital la *',
  'Titre du bundle *': 'Tit pakè a *',
  'Prix (HTG) *': 'Pri (HTG) *',
  'Prix (USD $)': 'Pri (USD $)',
  'Prix Carte (USD, optionnel)': 'Pri kat (USD, si ou vle)',
  'En Gourdes (HTG).': 'An goud (HTG).',
  'Requis pour le paiement par carte USD': 'Obligatwa pou peman ak kat an USD',
  'Gratuit': 'Gratis',
  'Disponible sans paiement': 'Disponib san peman',
  'Accessible sans paiement': 'Aksesib san peman',
  'Visible au catalogue': 'Parèt nan katalòg la',
  'Visible dans votre catalogue': 'Parèt nan katalòg ou a',
  'Publié': 'Pibliye',
  'Publiés': 'Pibliye',
  'Publiés au catalogue': 'Pibliye nan katalòg la',
  'Brouillon': 'Bouyon',
  'Brouillons': 'Bouyon yo',
  'Brouillons hors-ligne': 'Bouyon ki pa sou entènèt',
  'Tarification & Publication': 'Pri ak piblikasyon',
  'Tarification & Visibilité': 'Pri ak vizibilite',
  'Aperçu de la couverture': 'Apèsi kouvèti a',
  'Aperçu en direct (Live Preview)': 'Apèsi dirèk',
  'Aperçu en temps réel chez vos élèves :': 'Sa elèv ou yo ap wè tousuit :',
  'Image de couverture du cours': 'Imaj kouvèti kou a',
  'Image de couverture (Optionnel)': 'Imaj kouvèti (si ou vle)',
  'Image de présentation du bundle': 'Imaj prezantasyon pakè a',
  'Visuel qui apparaîtra dans le catalogue': 'Imaj k ap parèt nan katalòg la',
  'Aucun logo': 'Pa gen logo',
  'Annuler le logo sélectionné': 'Anile logo ou chwazi a',
  'Choisir une nouvelle image': 'Chwazi yon nouvo imaj',
  'Cliquez pour charger l’image': 'Klike pou chaje imaj la',
  "Cliquez pour charger l'image": 'Klike pou chaje imaj la',
  'Cliquez pour téléverser une image de présentation': 'Klike pou telechaje yon imaj prezantasyon',
  'Formats acceptés : PNG, JPG ou WEBP — 2 Mo maximum.': 'Fòma yo aksepte : PNG, JPG oswa WEBP — 2 Mo maksimòm.',
  '(Optionnel)': '(Si ou vle)',
  'Au moins 2 requis': 'Omwen 2 obligatwa',
  'Non fourni': 'Pa bay',
  'Non défini': 'Pa defini',
  'Fichier local': 'Fichye lokal',
  'Lien URL (HTTPS)': 'Lyen URL (HTTPS)',
  'Lien YouTube, Vimeo, Loom ou MP4 direct pour la vidéo de présentation sur la page du cours (optionnel).': 'Lyen YouTube, Vimeo, Loom oswa MP4 dirèk pou videyo prezantasyon kou a (si ou vle).',
  'Lien YouTube, Vimeo, Loom ou MP4 pour la bande-annonce sur la page publique.': 'Lyen YouTube, Vimeo, Loom oswa MP4 pou trelè a sou paj piblik la.',
  'Saisissez un lien YouTube, Vimeo ou MP4 ci-dessus pour activer la visualisation.': 'Antre yon lyen YouTube, Vimeo oswa MP4 anlè a pou gade videyo a.',
  'Saisissez l’adresse HTTPS directe de l’image.': 'Antre adrès HTTPS dirèk imaj la.',
  "Saisissez l'adresse HTTPS directe de l'image.": 'Antre adrès HTTPS dirèk imaj la.',
  'URL de la vidéo (YouTube, Vimeo, Loom, MP4...)': 'URL videyo a (YouTube, Vimeo, Loom, MP4...)',
  'Vidéo de présentation (URL optionnelle)': 'Videyo prezantasyon (URL si ou vle)',
  'Vidéo de présentation / Bande-annonce (URL optionnelle)': 'Videyo prezantasyon / trelè (URL si ou vle)',
  'Identifiant de variante Lemon Squeezy': 'Idantifyan varyant Lemon Squeezy',
  'Identifiant du variant de ce cours sur Lemon Squeezy.': 'Idantifyan varyant kou sa a sou Lemon Squeezy.',
  'Identifiant du variant de votre produit sur Lemon Squeezy.': 'Idantifyan varyant pwodui ou a sou Lemon Squeezy.',
  'Identifiant du variant produit sur votre compte Lemon Squeezy.': 'Idantifyan varyant pwodui a sou kont Lemon Squeezy ou.',
  'Génération automatique': 'Kreyasyon otomatik',
  'Gestion Automatique des Décalages :': 'Ajisteman lè otomatik :',
  'Conversion automatique en norme internationale UTC pour vos clients dans le monde entier': 'Konvèsyon otomatik an UTC pou kliyan ou yo nan lemonn antye',
  'Amérique (NY / HT)': 'Amerik (NY / Ayiti)',
  'Corée du Sud (Séoul)': 'Kore disid (Seoul)',
  'Europe (Paris)': 'Ewòp (Pari)',
  'Multi-Régions': 'Plizyè rejyon',
  '10 par page': '10 pa paj',
  '20 par page': '20 pa paj',
  '25 par page': '25 pa paj',
  '5 par page': '5 pa paj',
  '50 par page': '50 pa paj',
  '3 jours)': '3 jou)',
  '7 jours)': '7 jou)',
  '7 jours': '7 jou',
  '14 jours': '14 jou',
  '30 jours': '30 jou',
  '60 jours': '60 jou',
  '90 jours': '90 jou',
  '2xx — Succès': '2xx — Siksè',
  '4xx — Erreur client': '4xx — Erè kliyan',
  '5xx — Erreur serveur': '5xx — Erè sèvè',
  'Copier JSON': 'Kopye JSON',
  'Copié !': 'Kopye !',
  'Inspecter JSON': 'Enspekte JSON',
  'En-têtes Requête (Request Headers)': 'Antèt demann lan',
  'Payload Requête JSON (Request Payload)': 'Done demann JSON',
  'Réponse JSON (Response Payload)': 'Repons JSON',
  'Méthode & Route': 'Metòd ak chemen',
  'ID Requête:': 'ID demann :',
  'Requête': 'Demann',
  'Réponse': 'Repons',
  'Tous les statuts (en attente + en cours + résolu)': 'Tout estati yo (annatant + ankou + rezoud)',
  'Seulement En attente ⏳': 'Annatant sèlman ⏳',
  'Seulement En cours 🔄': 'Ankou sèlman 🔄',
  'Seulement Résolu ✅': 'Rezoud sèlman ✅',
  'Vous n’avez pas encore créé de bundle. Associez 2 à 30 produits pour proposer des packs avantageux.': 'Ou poko kreye okenn pakè. Mete 2 a 30 pwodui ansanm pou ofri pakè ki pi bon mache.',
  "Vous n'avez pas encore créé de bundle. Associez 2 à 30 produits pour proposer des packs avantageux.": 'Ou poko kreye okenn pakè. Mete 2 a 30 pwodui ansanm pou ofri pakè ki pi bon mache.',
  'Aucun bundle ne correspond à vos filtres de recherche.': 'Pa gen okenn pakè ki koresponn ak filtè rechèch ou yo.',
  'Aucun produit disponible': 'Pa gen okenn pwodui disponib',
  'Aucun produit ne correspond à votre recherche.': 'Pa gen okenn pwodui ki koresponn ak rechèch ou a.',
  'Suppression définitive': 'Efasman definitif',
  'Cette action est irréversible.': 'Ou pa ka anile aksyon sa a.',
  'Supprimer ce bundle ?': 'Efase pakè sa a ?',
  'Supprimer cet ebook ?': 'Efase liv dijital sa a ?',
  'Supprimer cette formation ?': 'Efase kou sa a ?',
  'Cette action supprimera': 'Aksyon sa a ap efase',
  'Cette action supprimera la formation': 'Aksyon sa a ap efase kou a',
  'définitivement': 'nèt',
  'de votre catalogue.': 'nan katalòg ou a.',
  'Cette page est prête à accueillir son futur contenu.': 'Paj sa a pare pou resevwa kontni li.',
  'Le formulaire sera ajouté dans une prochaine étape.': 'Y ap ajoute fòm nan nan yon pwochen etap.',
  'Retour à la liste': 'Retounen nan lis la',
  'Retour aux offres de coaching': 'Retounen nan lis òf konsèy yo',
  'Chargement des offres groupées…': 'Òf gwoupe yo ap chaje…',
  'En savoir plus': 'Aprann plis'
};

Object.assign(ht, {
  'Actions du cours': 'Aksyon pou kou a',
  'Actions utilisateur': 'Aksyon pou itilizatè a',
  'Affichage par page': 'Kantite pa paj',
  'Affiché à côté du prix HTG.': 'Parèt bò kote pri an goud la.',
  'Aperçu couverture': 'Apèsi kouvèti a',
  'Aperçu du logo': 'Apèsi logo a',
  'Bundle': 'Pakè',
  "Canaux utilisés pour l'assistance et les notifications clients.": 'Mwayen yo itilize pou asistans ak avi kliyan yo.',
  'Carte Lemon Squeezy': 'Kat Lemon Squeezy',
  "Ce logo sera affiché dans l'en-tête du site, les e-mails de confirmation et les reçus de paiement.": 'Logo sa a ap parèt nan tèt sit la, nan imèl konfimasyon yo ak sou resi peman yo.',
  'Client / User': 'Kliyan / itilizatè',
  'Configurez votre disponibilité horaire et vos coordonnées WhatsApp. Les réservations sont automatiquement adaptées au fuseau local de vos élèves en Amérique, Europe ou Asie.': 'Konfigire lè ou disponib ak kontak WhatsApp ou. Lè rezèvasyon yo ajiste otomatikman selon zòn lè elèv ou yo nan Amerik, Ewòp oswa Azi.',
  'Contenu texte de la leçon...': 'Kontni ekri leson an...',
  'Descendre': 'Desann',
  'Descendre la leçon': 'Desann leson an',
  'Descendre le module': 'Desann modil la',
  'Décrivez les compétences acquises et la valeur proposée dans cette offre groupée...': 'Dekri konpetans elèv yo ap genyen ak avantaj òf gwoupe sa a...',
  'Email :': 'Imèl :',
  'Entre 1 et 100 000 HTG.': 'Ant 1 ak 100 000 HTG.',
  'Fermer la fenêtre': 'Fèmen fenèt la',
  'Fermer la notification': 'Fèmen avi a',
  'Fermer le détails du log': 'Fèmen detay jounal la',
  'Fermer le panneau': 'Fèmen panèl la',
  'Fermer les détails': 'Fèmen detay yo',
  'Filtrer les cours et e-books...': 'Filtre kou ak liv dijital yo...',
  'Filtrer par famille de statut HTTP': 'Filtre selon gwoup estati HTTP',
  'Filtrer par statut :': 'Filtre selon estati :',
  'Horizon ouvert': 'Peryòd ouvè',
  "Les modifications sont conservées localement et synchronisées lors de l'enregistrement.": 'Chanjman yo rete sou aparèy la epi yo senkronize lè ou anrejistre.',
  'Leçon': 'Leson',
  'Menu administrateur': 'Meni administratè',
  'Modifier infos (Drawer)': 'Modifye enfòmasyon',
  'Monter': 'Monte',
  'Monter la leçon': 'Monte leson an',
  'Monter le module': 'Monte modil la',
  'Navigation d’administration': 'Navigasyon administrasyon',
  "Numéro WhatsApp de l'instructeur": 'Nimewo WhatsApp antrenè a',
  'Offres groupées · DJR Akademi Admin': 'Òf gwoupe yo · Administrasyon DJR Akademi',
  'Page': 'Paj',
  'Pour': 'Pou',
  'Présentez le contenu et les avantages de votre ebook...': 'Prezante kontni ak avantaj liv dijital ou a...',
  'Présentez le programme de votre formation...': 'Prezante pwogram kou ou a...',
  'Rechercher par client, email ou référence': 'Chèche selon kliyan, imèl oswa referans',
  'Rechercher par e-mail, référence, ID utilisateur ou message...': 'Chèche selon imèl, referans, ID itilizatè oswa mesaj...',
  'Rechercher par endpoint, commande ou transaction...': 'Chèche selon pwen aksè, kòmand oswa tranzaksyon...',
  'Rechercher par message, produit, WhatsApp...': 'Chèche selon mesaj, pwodui oswa WhatsApp...',
  'Rechercher par nom ou email...': 'Chèche selon non oswa imèl...',
  'Rechercher par titre ou produit inclus...': 'Chèche selon tit oswa pwodui ki ladan l...',
  'Rechercher un client…': 'Chèche yon kliyan…',
  'Rechercher un cours...': 'Chèche yon kou...',
  'Rechercher un ebook...': 'Chèche yon liv dijital...',
  'Rédigez le texte de la leçon...': 'Ekri tèks leson an...',
  'Rédigez votre réponse au client ici...': 'Ekri repons ou pou kliyan an isit la...',
  'Réduire ou développer tous les modules': 'Fèmen oswa louvri tout modil yo',
  'Résumé coaching': 'Rezime sesyon konsèy yo',
  'Sections de l’offre': 'Seksyon òf la',
  'Services': 'Sèvis yo',
  'Supprimer la leçon': 'Efase leson an',
  'Supprimer le module': 'Efase modil la',
  'Supprimer les anciens tickets': 'Efase ansyen demann yo',
  'Table des cours': 'Tablo kou yo',
  'Table des utilisateurs': 'Tablo itilizatè yo',
  'Titre de la leçon': 'Tit leson an',
  'Titre du module': 'Tit modil la',
  'Titre du module (ex: Module 1 — Introduction)': 'Tit modil la (egzanp : Modil 1 — Entwodiksyon)',
  "Tous vos créneaux sont enregistrés en norme UTC. Lorsque des clients réservent depuis la Corée du Sud, les États-Unis ou l'Europe, les heures s'adaptent instantanément à leur heure locale sans aucun risque d'erreur d'inattention.": 'Tout plas ou yo anrejistre an UTC. Lè kliyan nan Kore disid, Etazini oswa Ewòp fè yon rezèvasyon, lè yo ajiste otomatikman selon lè lokal yo.',
  'Type': 'Kalite',
  'Utilisateur (ID)': 'Itilizatè (ID)',
  'Utilisateurs · Administration': 'Itilizatè yo · Administrasyon',
  'Voir le ticket': 'Gade demann nan',
  'Vue grille': 'Gade an kadriyaj',
  'Vue tableau': 'Gade an tablo',
  'Étudiants': 'Elèv yo',
  'Êtes-vous sûr de vouloir supprimer l’offre groupée': 'Èske ou sèten ou vle efase òf gwoupe a',
  '? Cette action est irréversible et supprimera l’offre du catalogue public.': '? Ou pa ka anile aksyon sa a; li ap retire òf la nan katalòg piblik la.',
  'Créée le': 'Kreye nan dat',
  'de statut «': 'ki gen estati «',
  "n'aura plus accès à ses cours et ebooks tant que son compte restera désactivé.": 'p ap kapab jwenn aksè nan kou ak liv dijital li yo toutotan kont li dezaktive.',
  'ou glissez-déposez le fichier ici (JPG, PNG, WEBP)': 'oswa trennen fichye a depoze l isit la (JPG, PNG, WEBP)',
  'ou glissez-déposez le fichier ici (JPG, PNG, WEBP, max 10 MB)': 'oswa trennen fichye a depoze l isit la (JPG, PNG, WEBP, 10 Mo maksimòm)',
  'sur': 'sou',
  'à': 'a',
  'jours': 'jou',
  'minutes': 'minit',
  'apprenants': 'elèv',
  'commandes': 'kòmand',
  'utilisateurs': 'itilizatè',
  'offres au total': 'òf an total',
  'tentative': 'tantativ',
  'ticket(s)': 'demann',
  'créés il y a plus de': 'ki te kreye sa gen plis pase',
  '· Administration': '· Administrasyon',
  '· Fiche Utilisateur': '· Fich itilizatè',
  '· DJR Akademi': '· DJR Akademi',
  '3. Sélection des produits inclus': '3. Chwazi pwodui ki ladan l yo',
  'Produits inclus': 'Pwodui ki ladan l yo',
  'Cette action est irréversible et supprimera l’offre du catalogue public.': 'Ou pa ka anile aksyon sa a; li ap retire òf la nan katalòg piblik la.',
  '. Cette action est irréversible.': '. Ou pa ka anile aksyon sa a.',
  'Aucun bundle ne correspond à vos filtres de recherche.': 'Pa gen okenn pakè ki koresponn ak filtè rechèch ou yo.',
  'Ex. Pack Ultime Productivité & entelijans atifisyèl': 'Egzanp : Pakè pwodiktivite ak entèlijans atifisyèl',
  'Ex. Plateforme de formation & coaching en ligne': 'Egzanp : Platfòm kou ak sesyon konsèy sou entènèt',
  'Ex: Marketing Digital pour Créateurs': 'Egzanp : Maketing dijital pou kreyatè',
  'Ex: 🔥 Promotion de lancement : -50% sur tous les cours cette semaine !': 'Egzanp : 🔥 Pwomosyon lansman : 50 % rabè sou tout kou semèn sa a !'
});

Object.assign(ht, {
  'Accès ajouté avec succès': 'Aksè a ajoute avèk siksè',
  'Aperçu global des performances et de l’activité en temps réel.': 'Apèsi jeneral sou pèfòmans ak aktivite yo an tan reyèl.',
  'Assistance client': 'Sipò kliyan',
  'Bienvenue dans la formation': 'Byenveni nan kou a',
  'Bienvenue dans la leçon': 'Byenveni nan leson an',
  'Catalogue et services': 'Katalòg ak sèvis',
  'Console d’administration': 'Panèl administrasyon',
  'Cours mis à jour avec succès.': 'Kou a mete ajou avèk siksè.',
  'Ebook créé avec succès.': 'Liv dijital la kreye avèk siksè.',
  'Ebook mis à jour avec succès.': 'Liv dijital la mete ajou avèk siksè.',
  'Erreur lors de la création du coaching.': 'Te gen yon erè pandan kreyasyon sèvis konsèy la.',
  'Erreur lors de la mise à jour du service.': 'Te gen yon erè pandan mizajou sèvis la.',
  'Erreur lors de la purge.': 'Te gen yon erè pandan netwayaj la.',
  'Erreur lors de la sauvegarde des paramètres dans Appwrite.': 'Te gen yon erè pandan anrejistreman paramèt yo nan Appwrite.',
  'Erreur lors de la suppression des logs.': 'Te gen yon erè pandan efasman jounal yo.',
  'Erreur lors de l’enregistrement des leçons.': 'Te gen yon erè pandan anrejistreman leson yo.',
  'Erreur lors du changement de statut': 'Te gen yon erè pandan chanjman estati a',
  'Erreur lors du changement de statut.': 'Te gen yon erè pandan chanjman estati a.',
  'Erreur lors du chargement des tickets de support.': 'Te gen yon erè pandan chajman demann asistans yo.',
  'Finances et ventes': 'Finans ak lavant',
  'Impossible de charger la santé de l’API.': 'Pa kapab chaje eta API a.',
  'Impossible de charger le tableau de bord.': 'Pa kapab chaje tablo kontwòl la.',
  'Impossible de charger les commandes.': 'Pa kapab chaje kòmand yo.',
  'Impossible de charger les cours.': 'Pa kapab chaje kou yo.',
  'Impossible de charger les ebooks.': 'Pa kapab chaje liv dijital yo.',
  'Impossible de charger les journaux de vérification.': 'Pa kapab chaje jounal verifikasyon yo.',
  'Impossible de charger les offres groupées.': 'Pa kapab chaje òf gwoupe yo.',
  'Impossible de charger les paramètres.': 'Pa kapab chaje paramèt yo.',
  'Impossible de charger les utilisateurs.': 'Pa kapab chaje itilizatè yo.',
  "Impossible de créer l'ebook.": 'Pa kapab kreye liv dijital la.',
  "Impossible de mettre à jour l'ebook.": 'Pa kapab mete liv dijital la ajou.',
  'Impossible de mettre à jour le ticket.': 'Pa kapab mete demann nan ajou.',
  'Impossible de modifier le statut de la réservation.': 'Pa kapab chanje estati rezèvasyon an.',
  'Impossible de réactiver cet utilisateur.': 'Pa kapab reaktive itilizatè sa a.',
  'Impossible de supprimer le cours.': 'Pa kapab efase kou a.',
  'Impossible de supprimer l’ebook.': 'Pa kapab efase liv dijital la.',
  'Impossible de supprimer l’offre groupée.': 'Pa kapab efase òf gwoupe a.',
  'Impossible d’ajouter cet accès.': 'Pa kapab ajoute aksè sa a.',
  'Impossible d’enregistrer le cours.': 'Pa kapab anrejistre kou a.',
  'Impossible d’enregistrer les paramètres.': 'Pa kapab anrejistre paramèt yo.',
  'Impossible d’enregistrer l’offre groupée.': 'Pa kapab anrejistre òf gwoupe a.',
  'Impossible d’ouvrir la session utilisateur.': 'Pa kapab louvri sesyon itilizatè a.',
  'Informations du cours mises à jour.': 'Enfòmasyon kou a mete ajou.',
  "L'image est trop volumineuse. La taille maximale autorisée est de 10 MB.": 'Imaj la twò gwo. Gwosè maksimòm lan se 10 Mo.',
  'Le cours a été supprimé avec succès.': 'Kou a efase avèk siksè.',
  'Le fuseau horaire sélectionné est invalide.': 'Zòn lè ou chwazi a pa valab.',
  'Le logo doit être au format PNG, JPG ou WEBP.': 'Logo a dwe nan fòma PNG, JPG oswa WEBP.',
  'Le logo ne doit pas dépasser 2 Mo.': 'Logo a pa dwe depase 2 Mo.',
  'Le numéro WhatsApp doit respecter le format international (+509..., +1..., +33...).': 'Nimewo WhatsApp la dwe respekte fòma entènasyonal la (+509..., +1..., +33...).',
  'Le prix doit être un montant entier compris entre 1 et 100 000 HTG.': 'Pri a dwe yon nonb antye ant 1 ak 100 000 HTG.',
  'Le titre et la description sont obligatoires.': 'Tit la ak deskripsyon an obligatwa.',
  'Les paramètres généraux et le logo ont été enregistrés avec succès.': 'Paramèt jeneral yo ak logo a anrejistre avèk siksè.',
  'L’offre groupée a été supprimée.': 'Òf gwoupe a efase.',
  'Modifications enregistrées avec succès.': 'Chanjman yo anrejistre avèk siksè.',
  'Mon profil': 'Pwofil mwen',
  'Nouveau coaching': 'Nouvo sèvis konsèy',
  'Nouveau contenu': 'Nouvo kontni',
  'Nouveau cours créé avec succès.': 'Nouvo kou a kreye avèk siksè.',
  'Nouvel Ebook': 'Nouvo liv dijital',
  'Nouvelle leçon': 'Nouvo leson',
  'Nouvelle offre groupée créée avec succès !': 'Nouvo òf gwoupe a kreye avèk siksè !',
  'Offre de coaching créée avec succès.': 'Òf sesyon konsèy la kreye avèk siksè.',
  'Offre groupée mise à jour avec succès !': 'Òf gwoupe a mete ajou avèk siksè !',
  'Ouvrir le menu': 'Louvri meni an',
  'Paramètres de coaching enregistrés avec succès.': 'Paramèt sesyon konsèy yo anrejistre avèk siksè.',
  'Programme et leçons enregistrés avec succès !': 'Pwogram nan ak leson yo anrejistre avèk siksè !',
  'Santé et journaux API': 'Eta sistèm nan ak jounal API',
  'Seuls les fichiers PDF sont acceptés pour les ebooks.': 'Se fichye PDF sèlman yo aksepte pou liv dijital yo.',
  'Statut de la réservation mis à jour avec succès.': 'Estati rezèvasyon an mete ajou avèk siksè.',
  'Super Admin': 'Administratè prensipal',
  'Système actif': 'Sistèm aktif',
  'Système dégradé': 'Sistèm nan gen pwoblèm',
  'Système et supervision': 'Sistèm ak siveyans',
  'Système indisponible': 'Sistèm nan pa disponib',
  'Système opérationnel': 'Sistèm nan ap fonksyone',
  'Sélectionnez au moins deux produits (formations ou livres numériques) pour créer une offre groupée.': 'Chwazi omwen de pwodui (kou oswa liv dijital) pou kreye yon òf gwoupe.',
  'Ticket de support mis à jour avec succès.': 'Demann asistans lan mete ajou avèk siksè.',
  'Utilisateur désactivé': 'Itilizatè dezaktive',
  'Utilisateur désactivé avec succès.': 'Itilizatè a dezaktive avèk siksè.',
  'Utilisateur réactivé': 'Itilizatè reaktive',
  'Utilisateur réactivé avec succès': 'Itilizatè a reaktive avèk siksè',
  'Utilisateur réactivé avec succès.': 'Itilizatè a reaktive avèk siksè.',
  'Veuillez entrer un prix valide supérieur à 0 HTG.': 'Antre yon pri valab ki pi wo pase 0 HTG.',
  'Veuillez sélectionner un fichier image valide (JPG, PNG, WEBP).': 'Chwazi yon fichye imaj valab (JPG, PNG, WEBP).',
  'Voir le site': 'Gade sit la',
  'Vue principale': 'Paj prensipal',
  'Échec du changement de statut.': 'Chanjman estati a echwe.',
  'État inconnu': 'Eta enkoni'
});

Object.assign(ht, {
  'Modifier le cours': 'Modifye kou a',
  'Modifier l’offre groupée': 'Modifye òf gwoupe a',
  'Créer une nouvelle offre groupée': 'Kreye yon nouvo òf gwoupe',
  'Créer l’offre groupée': 'Kreye òf gwoupe a',
  "Créer l'offre de coaching": 'Kreye òf sesyon konsèy la',
  'Aucun appel Plopplop enregistré pour le moment.': 'Poko gen okenn apèl Plopplop ki anrejistre.',
  'Chargement des logs…': 'Jounal yo ap chaje…',
  'Détection en cours…': 'Deteksyon ankou…',
  'Développer le module': 'Louvri modil la',
  'Développer tout': 'Louvri tout',
  'Réduire le module': 'Fèmen modil la',
  'Réduire tout': 'Fèmen tout',
  'Leçon sans titre': 'Leson san tit',
  'Mettez à jour les informations et la composition de ce pack.': 'Mete enfòmasyon ak kontni pakè sa a ajou.',
  'Non configuré': 'Pa konfigire',
  'Non renseigné': 'Pa bay',
  'Numéro WhatsApp Officiel': 'Nimewo WhatsApp ofisyèl',
  'Remplissez les détails et sélectionnez les formations/e-books à inclure.': 'Ranpli detay yo epi chwazi kou ak liv dijital pou mete ladan l.',
  'Téléverser une image de couverture': 'Telechaje yon imaj kouvèti',
  'Vidéo Directe': 'Videyo dirèk',
  'Votre message d’annonce apparaîtra ici tout en haut du site.': 'Mesaj anons ou a ap parèt isit la anlè sit la.',
  "L'ebook a été supprimé avec succès.": 'Liv dijital la efase avèk siksè.',
  "Impossible de téléverser l'image de couverture.": 'Pa kapab telechaje imaj kouvèti a.'
});

// Text produced by counts or labels with a variable part.
const patterns: [RegExp, (match: RegExpMatchArray) => string][] = [
  [/^(\d+) utilisateurs?$/, (m) => `${m[1]} itilizatè`],
  [/^(\d+) commandes?$/, (m) => `${m[1]} kòmand`],
  [/^(\d+) offres? au total$/, (m) => `${m[1]} òf an total`],
  [/^(\d+) apprenants?$/, (m) => `${m[1]} elèv`],
  [/^(\d+) jours?$/, (m) => `${m[1]} jou`],
  [/^(\d+) minutes?$/, (m) => `${m[1]} minit`],
  [/^(\d+) ventes? validées?$/, (m) => `${m[1]} lavant valide`],
  [/^(\d+) apprenants actifs \(0 bloqué\)$/, (m) => `${m[1]} elèv aktif (0 bloke)`],
  [/^Page (\d+) sur (\d+)$/, (m) => `Paj ${m[1]} sou ${m[2]}`],
  [/^Inscrit le (.+)$/, (m) => `Enskri depi ${m[1]}`],
  [/^Créée le (.+)$/, (m) => `Kreye nan dat ${m[1]}`],
  [/^Ref Produit: (.+)$/, (m) => `Referans pwodui : ${m[1]}`],
  [/^Leçon (\d+) \/ (\d+)$/, (m) => `Leson ${m[1]} / ${m[2]}`],
  [/^(\d+) leçons? sur (\d+) modules?\.$/, (m) => `${m[1]} leson nan ${m[2]} modil.`],
  [/^(\d+) bloqués? \((\d+) actifs?\)$/, (m) => `${m[1]} bloke (${m[2]} aktif)`],
  [/^(\d+) à (\d+) sur (\d+) (commandes|ebooks|logs)$/, (m) => `${m[1]} a ${m[2]} sou ${m[3]} ${m[4] === 'commandes' ? 'kòmand' : m[4] === 'ebooks' ? 'liv dijital' : 'jounal'}`]
];

const months: Record<string, string> = {
  janvier: 'janvye', 'janv.': 'janv.', février: 'fevriye', 'févr.': 'fevr.',
  mars: 'mas', avril: 'avril', 'avr.': 'avr.', mai: 'me', juin: 'jen',
  juillet: 'jiyè', 'juil.': 'jiyè', août: 'out', septembre: 'septanm',
  'sept.': 'sept.', octobre: 'oktòb', 'oct.': 'okt.', novembre: 'novanm',
  'nov.': 'nov.', décembre: 'desanm', 'déc.': 'des.'
};

function translate(value: string): string {
  if (ht[value]) return ht[value];
  for (const [pattern, render] of patterns) {
    const match = value.match(pattern);
    if (match) return render(match);
  }
  if (/\d/.test(value)) {
    const localizedDate = value.replace(/\b(janvier|janv\.|février|févr\.|mars|avril|avr\.|mai|juin|juillet|juil\.|août|septembre|sept\.|octobre|oct\.|novembre|nov\.|décembre|déc\.)(?=\s|$)/gi, (month) => months[month.toLowerCase()] ?? month);
    if (localizedDate !== value) return localizedDate;
  }
  return value;
}

export function translateAdminMessage(value: string, language: Language): string {
  return language === 'ht' ? translate(value) : value;
}

type Translated = { source: string; rendered: string };
const textSources = new WeakMap<Text, Translated>();
const attributeSources = new WeakMap<Element, Map<string, Translated>>();
const attributes = ['placeholder', 'aria-label', 'title', 'alt'];
let allowFrenchNavigation = false;

export function allowNextFrenchAdminNavigation(): void {
  allowFrenchNavigation = true;
}

export function consumeFrenchAdminNavigation(): boolean {
  const allowed = allowFrenchNavigation;
  allowFrenchNavigation = false;
  return allowed;
}

export function localizeAdmin(root: HTMLElement, language: Language): () => void {
  const processText = (node: Text) => {
    if (!node.parentElement || node.parentElement.closest('script, style, textarea, [contenteditable="true"]')) return;
    const current = node.data;
    const previous = textSources.get(node);
    const source = previous && current === previous.rendered ? previous.source : current;
    const trimmed = source.trim();
    if (!trimmed) return;
    const translated = language === 'ht' ? translate(trimmed) : trimmed;
    const rendered = source.replace(trimmed, translated);
    textSources.set(node, { source, rendered });
    if (rendered !== current) node.data = rendered;
  };

  const processElement = (element: Element) => {
    if (element instanceof HTMLAnchorElement) {
      const href = element.getAttribute('href');
      if (href && (href === '/admin' || href.startsWith('/admin/') || href.startsWith('/admin?'))) {
        const url = new URL(href, location.origin);
        if (language === 'ht') url.searchParams.set('lang', 'ht');
        else url.searchParams.delete('lang');
        const localizedHref = url.pathname + url.search + url.hash;
        if (href !== localizedHref) element.setAttribute('href', localizedHref);
      }
    }
    let sources = attributeSources.get(element);
    if (!sources) {
      sources = new Map();
      attributeSources.set(element, sources);
    }
    for (const name of attributes) {
      const current = element.getAttribute(name);
      if (current === null) continue;
      const previous = sources.get(name);
      const source = previous && current === previous.rendered ? previous.source : current;
      const rendered = language === 'ht' ? translate(source) : source;
      sources.set(name, { source, rendered });
      if (rendered !== current) element.setAttribute(name, rendered);
    }
  };

  const visit = (node: Node) => {
    if (node.nodeType === Node.TEXT_NODE) processText(node as Text);
    else if (node.nodeType === Node.ELEMENT_NODE) {
      processElement(node as Element);
      for (const child of Array.from(node.childNodes)) visit(child);
    }
  };

  visit(root);
  const visitHead = () => {
    const title = document.head.querySelector('title');
    if (title) visit(title);
    const description = document.head.querySelector('meta[name="description"]');
    if (description) {
      const current = description.getAttribute('content');
      if (current) {
        let sources = attributeSources.get(description);
        if (!sources) {
          sources = new Map();
          attributeSources.set(description, sources);
        }
        const previous = sources.get('content');
        const source = previous && current === previous.rendered ? previous.source : current;
        const rendered = language === 'ht' ? translate(source) : source;
        sources.set('content', { source, rendered });
        if (rendered !== current) description.setAttribute('content', rendered);
      }
    }
  };
  visitHead();
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === 'characterData') visit(mutation.target);
      else if (mutation.type === 'attributes') visit(mutation.target);
      else for (const node of Array.from(mutation.addedNodes)) visit(node);
    }
  });
  observer.observe(root, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: [...attributes, 'href'] });
  const headObserver = new MutationObserver(visitHead);
  headObserver.observe(document.head, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: ['content'] });
  return () => { observer.disconnect(); headObserver.disconnect(); };
}
